### PR TITLE
Moved DI IServiceCollection to one from WebJobsStartup

### PR DESCRIPTION
**Pull request by alexeymarkov**
…dencies properly.

For instance, now IDisposable scoped dependencies such as DbContext are released properly.

### CODE REVIEW

**Comment by alexeymarkov** [comment]
Sure it should be added to all templates.

**Comment by alexeymarkov** [comment]
Instead of using own IServiceCollection and build it into IServiceProvider more clever solutions would be to use IServiceCollection directly from FunctionStatrtup and inject IServiceProvider into a function class. This IServiceProvider instance is already scoped and would allow injection of ILogger<T>, IConfiguration and everything else prepared for the function environment.

I will try to figure out how to implement it.

**Comment by alexeymarkov** [comment]
Good news: I almost finished the implementation but need a few hours to polish it.

**Comment by alexeymarkov** [comment]
I did not check for other triggers although I adjusted them too.
Now IServiceCollection/IServiceProvider from WebJobsStartup are used.

- ILogger<> works as well as ILogger
- IConfiguration works
- Scoped resources are released properly

**Comment by JamesRandall** [comment]
Many thanks for this everyone - super appreciated.

Its now in the v4 beta on master.

**Pull request merged**
